# c.f. https://github.com/commercialhaskell/stack/wiki/Travis
sudo: false

before_install:
  # enable stack
  - ./scripts/set-resolver.sh $RESOLVER > stack-travis.yaml
  - export STACK_YAML=stack-travis.yaml
  - mkdir -p ~/.local/bin
  - mkdir -p ~/.local/lib
  - export PATH=~/.local/bin:$PATH
  - export LD_LIBRARY_PATH=~/.local/lib:$LD_LIBRARY_PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup


matrix:
  include:
    - env: RESOLVER=lts-9  # GHC 8.0.2
    - env: RESOLVER=lts-11 # GHC 8.2.2
    - env: RESOLVER=lts-12 # GHC 8.4.4
    - env: RESOLVER=lts-14 # GHC 8.6.5
    - env: RESOLVER=nightly
  allow_failures:
    - env: RESOLVER=nightly

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - libgmp-dev

script:
  - stack --no-terminal --skip-ghc-check build --ghc-options=-ferror-spans
  - stack test
